services:
  redis:
    image: bitnami/redis:latest
    container_name: redis
    env_file:
      - ./.env
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/bitnami/redis/data'
    restart: always
    networks:
      - short_url_network
  app:
    image: short-url
    container_name: short-url
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
    ports:
      - '3000:3000'
    networks:
      - short_url_network
    depends_on:
      - redis

volumes:
  redis:

networks:
  short_url_network:
    driver: bridge
